### ISSUE TITLE
Fix: Antipontifex

### ISSUE THREAD

**Issue by Gitbone94** [iptv-org/iptv#10436]
### Describe your issue

Obvious we need a way to get rid of these 1.2k open fake issues

**Comment by LaneSh4d0w** [comment]
What makes you think it's "fake issues" ? If the channels he's proposing are in the playlist, then show a few.

And no, there's no "1.2k fake issues" AFAIK. I'm busy with work and my own projects and cannot deal with the issues right now

**Comment by AntiPontifex** [comment]
It's part of my plot; Gitbone94 has unmasked me! Well played, sir!

**Comment by Gitbone94** [comment]
Sure, we go from a hundred or so issues to 1,200+ and its the same couple of ids doing it. I look forward to seeing all these new channels.

**Comment by Smark223** [comment]
There does seem to be a lot of channel requests that surely no one is interested in. I don't dispute that they're valid channel streams but the number of requests/issues raised in recent weeks has made it very difficult to keep up. People are busy. I'm sure there are some stream proposals that would be useful that are getting lost amongst all the crap.

**Comment by AntiPontifex** [comment]
Don't feed the trolls.

**Comment by LaneSh4d0w** [comment]
> There does seem to be a lot of channel requests that surely no one is interested in. I don't dispute that they're valid channel streams but the number of requests/issues raised in recent weeks has made it very difficult to keep up. People are busy. I'm sure there are some stream proposals that would be useful that are getting lost amongst all the crap*.
> 
> *I realise that's subjective!

What's important to raise here is that I don't have the time I used to have before. 

I have work, family to help and other things and I've been recently more than detached in the repositories I operate due to these reasons. 
I would surely get back onto it once i'll have more time, but consider this message as a notice more than a warning or anything of some sort. If it feels stale, maybe it'll get unbloated in a few days, weeks or months, who knows.

Also, if you have massive numbers of channels you want to add, *please, please* do a PR instead of 100x issues, it'll gladly help us with sorting these out.
