### ISSUE TITLE
Add: Nazali's HDTV

### ISSUE THREAD

**Issue by Patrick3101** [iptv-org/iptv#12354]
### Channel ID

Www.nazalismedia.fr

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by Patrick3101** [comment]
I would like to add my Chanel on the playlist, is the anyone who can help me to do that ?

**Comment by BellezaEmporium** [comment]
Thank you for proposing your channel to us.
Please submit your channel first in our database, so that we can register it as a channel. We'll create a channel ID that we can put afterwards with your channel stream.

Found this : http://194.163.135.238:5080/WebRTCApp/streams/590264631485484547459082.m3u8

**Comment by Patrick3101** [comment]
Hello,
Can you send me the link to the database ?

**Comment by freearhey** [comment]
@Patrick3101 https://github.com/iptv-org/database
