### ISSUE TITLE
Add: BS11

### ISSUE THREAD

**Issue by ZXArkin** [iptv-org/iptv#13883]
### Channel ID

BS11.jp

### Stream URL (optional)

http://194.233.72.249:8080/BS11/index.m3u8

### Notes (optional)

![BS11_20230814_080235 840](https://github.com/iptv-org/iptv/assets/21299971/4e772dfb-006e-40d4-bb14-224e8d5db673)
Add test BS11 channel, the experminal thing.
If when change please comment here.

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by arecki2** [comment]
Just found a few more, as, well... I'm in a need for Japanese TV streams today 🤓

http://194.233.72.249:8080/NHKG/index.m3u8
http://194.233.72.249:8080/TVTOKYO/index.m3u8
http://194.233.72.249:8080/TVASAHI/index.m3u8
http://194.233.72.249:8080/NIPPONTV/index.m3u8
http://194.233.72.249:8080/FUJITV/index.m3u8
http://194.233.72.249:8080/TBS/index.m3u8

Can't reach more channels yet, especially more BS channels, perhaps they'll be added over time. Can't find their source though.

**Comment by Iri111** [comment]
These are all from the iptv-jp repository of luongz here at Github.  They are all test channels for now, and might change.
Since he and another person are actually paying for this server, I believe it would be good manners to hold off adding these.  
He also requested in the issues thread for these channels at his repository that these not be uploaded to another repository, which I think should be honored.

**Comment by BellezaEmporium** [comment]
Per what was said by @Iri111, closing this issue.
