### ISSUE TITLE
Separate "Latin America" playlist

### ISSUE THREAD

**Issue by opm0** [iptv-org/iptv#1432]
**Is your feature request related to a problem? Please describe.**
The "Spanish" playlist includes over-the-air local TV channels from every Spanish-speaking country.

**Describe the solution you'd like**
I want a separate playlist that only includes cable or pan-regional channels available in Latin America, such as DW Español, De Película, EWTN or CGTN Español.

**Describe alternatives you've considered**
- A playlist that includes all non-OTA Spanish-language TV channels (might be easier).
- Divide all language playlists between "OTA" and "non-OTA"

**Additional context**

**Comment by themak1985** [comment]
You could achieve most of what you want through proper labeling. If every local channel, or "OTA" as you call it is labeled Local, when you use the Spanish playlist, it organizes by Category and you can filter out the "Local" category. This should leave you with most of the channels that you want. Now I say most, because, non latin-american spanish channels would also be included, such as from USA, Spain, etc. Now your challenge will be going into each country that has spanish language channels as a language and labeling all "Local" channels as local. 

I have done similar before by labeling channels without languages with their appropriate languages. It may take you a few hours, but the project overall will benefit from your contribution.
