### ISSUE TITLE
Broken: WION is broken in in.m3u

### ISSUE THREAD

**Issue by andrew121410** [iptv-org/iptv#14395]
### Broken Link

https://d2xqcdx4c8vu9s.cloudfront.net/out/v1/15b8393e9a9240b8bedd4c79ccefb301/index.m3u8

### What happened to the stream?

Not loading

### Notes (optional)

All 3 WION URL's don't work in in.m3u

```
#EXTINF:-1 tvg-id="WION.in",WION (1080p)
https://d2xqcdx4c8vu9s.cloudfront.net/out/v1/15b8393e9a9240b8bedd4c79ccefb301/index.m3u8
#EXTINF:-1 tvg-id="WION.in",WION (1080p)
https://dai.google.com/linear/hls/event/x_dFvsORSZWERbxrltEk0g/master.m3u8
#EXTINF:-1 tvg-id="WION.in",Wion (576p)
http://210.210.155.37/uq2663/h/h91/index.m3u8
```

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Sphinxroot** [comment]
adaptative have token
https://d7x8z4yuq42qn.cloudfront.net/index.m3u8?akes=xxxTokenxxx

#EXTINF:-1 tvg-id="",WION (1080p)
https://d7x8z4yuq42qn.cloudfront.net/index_7.m3u8
#EXTINF:-1 tvg-id="",WION (720p)
https://d7x8z4yuq42qn.cloudfront.net/index_1.m3u8
#EXTINF:-1 tvg-id="",WION (504p)
https://d7x8z4yuq42qn.cloudfront.net/index_2.m3u8
#EXTINF:-1 tvg-id="",WION (480p)
https://d7x8z4yuq42qn.cloudfront.net/index_5.m3u8
#EXTINF:-1 tvg-id="",WION (360p)
https://d7x8z4yuq42qn.cloudfront.net/index_4.m3u8
#EXTINF:-1 tvg-id="",WION (240p)
https://d7x8z4yuq42qn.cloudfront.net/index_3.m3u8

**Comment by andrew121410** [comment]
Does the token change each hour? I get the token it works and then it just randomly stops working after like a hour.

**Comment by andrew121410** [comment]
So essentially I would have to make a program to catch the new token from the website each hour

**Comment by Sphinxroot** [comment]
well you won`t be able to use the adaptative as  hard coded ,  since it change  ,maybe using streamlink (pipe the  https://www.wionews.com/videos/live-tv.html?videoId=zee_wion&title=WION&extraParam1=WION&extraParam2=https://www.wionews.com/&taptounmute=0&mute=0&piv=0&pip=0&autoplay=1 or https://www.wionews.com/live-tv) 

index_x.m3u8  will work  without the token

and youtube have 20 lives  https://www.youtube.com/@WION  hard to have it hard coded on the one that realy count ,only on kodi with the addon and the api installed ,   you will be able to use all 20 streams
