### ISSUE TITLE
Broken: RajawaliTV.id

### ISSUE THREAD

**Issue by FlcristPony** [iptv-org/iptv#15565]
### Broken Link

https://cdn-telkomsel-01.akamaized.net/Content/HLS/Live/channel(41869351-4a9c-4e57-b54b-8cf5dfc919e1)/index.m3u8

### What happened to the stream?

Not loading

### Notes (optional)

Used to work before, now says "Resource not found".

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Dum4G** [comment]
@antosatriani if you have a minute, please verify if it has became geo-blocked or got broken

**Comment by antosatriani** [comment]
@Dum4G You're right Sir. Streaming from this source currently not available. I got a new one from unofficial source(http://iptvid.my.id/hmm/Gaboleh/gasukatugas123/rtv.m3u8). But I dont know how long it will work.

**Comment by FlcristPony** [comment]
Today I got this notice opening the link:
`Anda Telah Di Ban Admin: Gaboleh , Baca Kembali Rulesnya..!!`
EN: You're banned by admin: Not allowed, read the rules!
Other working link is appreciated.

**Comment by antosatriani** [comment]
Sorry Sir. I have been busy lately. Streaming from iptvid.my.id is no longer working, because this is not official broadcasting network. I have another one from Indihome. https://cdn09jtedge.indihometv.com/joss/130/rtv/index.m3u8
![Screenshot_2024-01-21-17-53-22-12_df198e732186825c8df26e3c5a10d7cd](https://github.com/iptv-org/iptv/assets/134463236/ed4840ff-75bd-4d53-8879-9e955e722e46)
