### ISSUE TITLE
Broken: MSNBC (1080p)

### ISSUE THREAD

**Issue by cguertin14** [iptv-org/iptv#15976]
### Broken Link

http://41.205.93.154/MSNBC/index.m3u8

### What happened to the stream?

Not loading

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by mnwachukwu** [comment]
Hi,

I have tested this URL again and it does not appear to be broken at this time. Rather than create another issue (several have been opened for this stream) I thought I would comment on the one issue with the latest action date.

I figured this way, it would imply the acknowledgement that at one time this was broken but after testing for about 5 minutes now, the stream seems to be working again.

My apologies if this violates protocols. I read the contributing guide and saw nothing about this particular issue, or anything about commenting on closed issues. If this is not preferred, I can open a new issue - or if you would prefer, I could roll my sleeves up and put in a PR for you guys.
