### ISSUE TITLE
CANAL RED1

### ISSUE THREAD

**Issue by TheMZPro** [iptv-org/iptv#16229]
### Channel ID (required)

https://www.mzproducciones.com/

### Channel Name

CANAL RED1

### Stream URL (required)

https://app.viloud.tv/hls/channel/3fb163ed91023cdc277bfa748c62e162.m3u8

### Quality

1080p

### Label

None

### HTTP Referrer

https://www.mzproducciones.com/

### Notes

Canal de Costa Rica

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by TheMZPro** [comment]
![301263078_419695370144333_2909078913471512100_n](https://github.com/iptv-org/iptv/assets/164399247/b72446ea-e388-4e59-bd05-f91160e0c31d)

**Comment by BellezaEmporium** [comment]
-> Unnecessary referrer on first check.
-> Wrong tvg-id.

Since I see you're the owner of the channel (and since we do not have it in our database), it is best to add it to our [database](https://github.com/iptv-org/database/issues/new?assignees=&labels=channels%3Aadd&projects=&template=__channels_add.yml&title=Add%3A+) first.

**Comment by Moratony** [comment]
https://github.com/iptv-org/database/issues/10609

**Comment by Moratony** [comment]
https://app.viloud.tv/hls/channel/3fb163ed91023cdc277bfa748c62e162.m3u8

**Comment by AntiPontifex** [comment]
I'll make a database entry, Belleza, to move this along.

**Comment by Alstruit** [comment]
Dead link.

**Comment by Moratony** [comment]
https://app.viloud.tv/hls/channel/13f265f9b0a5b3ad9b968124db986450.m3u8
