### ISSUE TITLE
Add: Now TV

### ISSUE THREAD

**Issue by Benedek012** [iptv-org/iptv#16414]
### Channel ID (required)

Nowtv.tr

### Stream URL (required)

https://www.nowtv.com.tr/canli-yayin

### Quality

720p

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by R4IN2007** [comment]
Wrong stream url and epg Id. Hey @Alstruit This is FOX Channel from Turkey has been rebranded as NOW. The problem is that the iptv-org.github.io database hasn't been updated with the correct info
https://iptv-org.github.io/channels/tr/Fox
Signal of BluTV still works and gets around the geo-blocked & Token from main stream
(https://foxtv.blutv.com/blutv_foxtv_live/live.m3u8)
![Screenshot_20240427_013619_Chrome](https://github.com/iptv-org/iptv/assets/83226646/4b544dcc-49d3-4adb-9f4b-4c2896e724bb)

**Comment by R4IN2007** [comment]
> Wrong stream url and epg Id. Hey @Alstruit This is FOX Channel from Turkey has been rebranded as NOW. The problem is that the iptv-org.github.io database hasn't been updated with the correct info https://iptv-org.github.io/channels/tr/Fox Signal of BluTV still works and gets around the geo-blocked & Token from main stream (https://foxtv.blutv.com/blutv_foxtv_live/live.m3u8) ![Screenshot_20240427_013619_Chrome](https://private-user-images.githubusercontent.com/83226646/326159991-4b544dcc-49d3-4adb-9f4b-4c2896e724bb.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQyMDAxMjgsIm5iZiI6MTcxNDE5OTgyOCwicGF0aCI6Ii84MzIyNjY0Ni8zMjYxNTk5OTEtNGI1NDRkY2MtNDlkMy00YWRiLTlmNGItNGMyODk2ZTcyNGJiLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI3VDA2MzcwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVkNDE3YzZlNjQ4ODQwYWZmZWU1MmFlYTc4NWMxMjNjODU1NzFkNzczY2FhYzA5YjVlMmE3YjNkYzgzMjk4OTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.v-eU7tTjc4y2dM0mnEDyHJ3lEdGn8oCNGBIaAuCnimA)

https://en.m.wikipedia.org/wiki/NOW_(Turkish_TV_channel)

**On 12 February 2024, the channel rebranded to Now as a part of Disney's planned phaseout of Fox brand following the acquisition of 21st Century Fox. Unlike other Fox-branded channels, the Turkish counterpart did not rebrand to Star Channel due to there being already a channel called Star TV in Turkey and the Turkish version of FX already existing in the region.**
