### ISSUE TITLE
Add: kstv

### ISSUE THREAD

**Issue by rizi136** [iptv-org/iptv#16887]
### Channel ID (required)

KilisuciTV.id

### Channel Name

Kilisuci TV

### Stream URL (required)

https://5bf7b725107e5.streamlock.net:443/kstv/kstv/playlist.m3u8

### Quality

None

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by rizi136** [comment]
![Uploading Screenshot_2024-06-26_143040.jpg…]()

**Comment by rizi136** [comment]
![Uploading Screenshot_2024-06-26_142441.jpg…]()

**Comment by olstern01** [comment]
In order to upload pictures successfully, you need to wait before pressing the comment button so that it will turn from this:

![Screenshot 2024-06-26 154706](https://github.com/iptv-org/iptv/assets/47495790/92c17620-12bc-441c-a8b7-653d147c1092)

to this:

![Screenshot 2024-06-26 154727](https://github.com/iptv-org/iptv/assets/47495790/07c4099a-bbd4-4451-b6c2-08087f48fd7e)

**Comment by rizi136** [comment]
![Screenshot_2024-06-26_143040](https://github.com/iptv-org/iptv/assets/173884781/9c639d76-b29d-49ca-bab1-2ffde620654a)

**Comment by rizi136** [comment]
![Screenshot_2024-06-26_142441](https://github.com/iptv-org/iptv/assets/173884781/7bacb7ca-be4d-44a4-8302-073e5ddf385e)

**Comment by olstern01** [comment]
Nice job. The stream works on VLC as well.

**Comment by olstern01** [comment]
I've created a new issue on https://github.com/iptv-org/database/issues , need to wait until it's approved.

**Comment by olstern01** [comment]
![Screenshot 2024-06-29 060900](https://github.com/iptv-org/iptv/assets/47495790/5c94829f-7d4f-44c2-8797-c16a6a82a310)

The database entry has been approved.  Please change the Channel ID of this issue to the one from the database.
