### ISSUE TITLE
how do you setup EPG? EDIT: usa and canada epg broken

### ISSUE THREAD

**Issue by foxtrotdragon** [iptv-org/iptv#1703]
I have tried to setup EPG using the main m3u link and http://epg.streamstv.me/epg/main.xml but it fails to populate

same with US and its EPG as well as Canada and its EPG

are they broken or am I doing something wrong?
I have tried Kodi(windows) myIPTV (windows) IPTV Smarters pro (android) and Perfect Player (android)

Again each one just fails to load the EPG entirely

EDIT: I think its just broken as I tried using Frugal streamers playlist and and EPG and albiet fairly empty some do show up

**Comment by bertperrisor** [comment]
Did you check if the EPG:

- Contain the correct tvg-id (has to match the one in the playlist); AND
- Correct timezone

You can't just simply load data in a player without checking it first. If the EPG contains broken data or simply does not match your playlist, it will never work.

**Comment by foxtrotdragon** [comment]
Is there any clear documentation I can read u on these? the playlist given for us.m3u and ca.m3u has all of the tvg-id="" and the given epgs seem to be outdated and i am quite confused on the matter I am unsure as the epgs show programme start = info is quite outdated showing 2020032913300 for the start date of one of them. 

The epg stream link for canada;
http://epg.streamstv.me/epg/guide-canada.xml.gz
The epg stream link for US;
http://epg.streamstv.me/epg/guide-usa.xml.gz

**Comment by bertperrisor** [comment]
You're using a very old EPG. They were never updated since March. 99% the data there is very old so they won't show up for present programmes. Very little possibility that the March EPG contains data until today. Usually EPGs are updated weekly, so you'll need to find a new EPG source.

<img width="1036" alt="Screenshot 2020-08-25 at 1 11 53 PM" src="https://user-images.githubusercontent.com/22504259/91125603-b4438300-e6d4-11ea-88b8-3c3346d2f8ba.png">
<img width="1037" alt="Screenshot 2020-08-25 at 1 11 58 PM" src="https://user-images.githubusercontent.com/22504259/91125606-b60d4680-e6d4-11ea-8ab7-e786a97c93dd.png">

**Comment by freearhey** [comment]
Unfortunately, EPGs are really outdated. I've already removed the links to them from the playlists, but as soon as the replacement is available we will return them.
