### ISSUE TITLE
Add: Crave 1 (CA)

### ISSUE THREAD

**Issue by boogabooga841** [iptv-org/iptv#17278]
### Channel ID (required)

Crave1.ca

### Channel Name

Crave 1

### Stream URL (required)

http://fl3.moveonjoy.com/CRAVE_1/index.m3u8

### Quality

None

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by ILIKECATS187** [comment]
BELL CANADA has already been DMCA comaplaint strike when we post CTV or NOOVO so they will come right away at these since they own CRAVE....

I suggest you keep those for yourself and even delete them has it will just bring heat onto this repo which I REPEAT IS RESERVED FOR FREE TO AIR CHANNELS ONLY ... dunno how all these new members are posting Piracy now but it use to be not allowed for YEARS on here and now few bad apples are burning all the links here

**Comment by ILIKECATS187** [comment]
> > BELL CANADA has already been DMCA comaplaint strike when we post CTV or NOOVO so they will come right away at these since they own CRAVE....
> > I suggest you keep those for yourself and even delete them has it will just bring heat onto this repo which I REPEAT IS RESERVED FOR FREE TO AIR CHANNELS ONLY ... dunno how all these new members are posting Piracy now but it use to be not allowed for YEARS on here and now few bad apples are burning all the links here
> 
> stop flooding this repository, go whine in your philippine forum or wharever



I dont know wtf you talking about phillipine and forums 

you sound crazy unwell and racist AF total cognitive dissonance I WONT TAKE THREATS FROM YOU IS THAT CLEAR  ........ check the description of the REPO you fucking tard ... FREE TO AIR TV not piracy this has been around for years no issues until people like you and Dum4 started showing up......

**Comment by Sphinxroot** [comment]
CTV and Noovo have never been dmca  , we use to have it until they have moved to dmr  stream , bell  now stream ctv  on samsung tv+  10 channels   , as for corus (global news) ..the have dmca  all over the place for legitimate non dmr stream ,but now the stream it on pluto tv ....  

but i crave w ont last long since its cable tv
