### ISSUE TITLE
Broken: Fox Lies Channel

### ISSUE THREAD

**Issue by Cringe-Arab** [iptv-org/iptv#17799]
### Broken Link

http://fl2.moveonjoy.com/FOX_News_Channel/index.m3u8

### What happened to the stream?

Not loading

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by JohnTCarter1** [comment]
Same issue since yesterday afternoon. This was the best Fox News Channel USA stream available (high quality and zero lag).

**Comment by JohnTCarter1** [comment]
I have been watching this one before and since yesterday afternoon again, but while the quality of the image is good, the sound sometimes disappears or there is a delay with the image/sound and some lag/complete interruption at times as well. Hope someone will be able to find/share a better link. Thank you!
