### ISSUE TITLE
Antigua and Barbuda channel

### ISSUE THREAD

**Issue by southerndream56** [iptv-org/iptv#1810]
There's new free channel from Antigua and Barbuda, ABS TV
https://www.lyngsat-stream.com/tvchannels/ag/ABS-TV.html
Could you add it to the list please?

Thanks

**Comment by Sphinxroot** [comment]
Hi 

since its a twitch channel and link is token other than that the .m3u8 link wont last and needed to be updated regulary

u might wanna use Kodi with the Twitch addon and use this in your own playlist .m3u 

# https://www.twitch.tv/absliveantigua3 #
#EXTINF:-1 tvg-logo="http://abstvradio.com/files/2014/12/ABS-Logo_sm.png" group-title="",ABS TV (TWITCH)
plugin://plugin.video.twitch/?channel_id=492332740&amp;mode=play

hope it help you

**Comment by freearhey** [comment]
Closed in favor #1987
