### ISSUE TITLE
Add: all lebanese channels 

### ISSUE THREAD

**Issue by mwehbe357** [iptv-org/iptv#2309]
**Channel Name:** xxx
**Country:** xxx
**Language:** xxx
**External Link (optional):** xxx
**Notes (optional):** xxx

**Comment by trancer1994** [comment]
What exactly do you want us to add? Are you saying the whole Lebanese playlist is broken?

**Comment by themak1985** [comment]
Closing, per [contributing guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel): To request a channel, create an issue and complete all details requested. (IMPORTANT: the issue should contain a request for only one channel, otherwise it will be closed immediately). Understand that our community of volunteers will try to help you, but if a public link cannot be found, there is little we can do.

**Comment by mwehbe357** [comment]
Mtv, new tv, nbn, are not available
Otv, future tv, lbc, are brokrn

Thank you

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by trancer1994** [comment]
Future TV
https://futuretv.cdn.mangomolo.com/futuretv/smil:futuretv.smil/playlist.m3u8

**Comment by trancer1994** [comment]
NBN
https://nbntv.me:8443/nbntv/index.m3u8

**Comment by freearhey** [comment]
@trancer1994 Added.

**Comment by Bakral24** [comment]
Lbci

**Comment by Wolfy361** [comment]
LBC International, LBC Europe, LB2
