### ISSUE TITLE
FOX Sports HD 1 is missing an "s" in the name

### ISSUE THREAD

**Issue by exigente82** [iptv-org/iptv#2411]
#EXTINF:-1 tvg-id="FOXSportHD1.us" tvg-name="FOX Sport HD 1" tvg-country="US" tvg-language="English" tvg-logo="" tvg-url="" group-title="Sport",FOX Sport HD 1 (720p)
https://austchannel-live.akamaized.net/hls/live/2002736/austchannel-sport/master.m3u8

**Comment by tokio491134** [comment]
Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                From: exigente82Sent: Wednesday, 14 April 2021 13:58To: iptv-org/iptvReply To: iptv-org/iptvCc: SubscribedSubject: [iptv-org/iptv] FOX Sports HD 1 is missing an "s" in the name (#2411)
#EXTINF:-1 tvg-id="FOXSportHD1.us" tvg-name="FOX Sport HD 1" tvg-country="US" tvg-language="English" tvg-logo="" tvg-url="" group-title="Sport",FOX Sport HD 1 (720p)
https://austchannel-live.akamaized.net/hls/live/2002736/austchannel-sport/master.m3u8

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/iptv-org/iptv/issues/2411",
"url": "https://github.com/iptv-org/iptv/issues/2411",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by freearhey** [comment]
Corrected.
