### ISSUE TITLE
Maltese Channel Requests

### ISSUE THREAD

**Issue by freearhey** [iptv-org/iptv#2506]
List of requests for Maltese channels from other issues:

- [x] [TVM](https://www.tvm.com.mt/mt/tvmi/live/tvm/) (#2491) (added via #2992)
- [ ] [NET](https://netondemand.mt/) (#2494)

**Comment by LaneSh4d0w** [comment]
TVM is into this JSON : 
https://media.tvm.com.mt/api/concatenate?format=json&raw=1&playersettings_0=%2Fapi%2Fplayer%2Fsettings%3Fplayer_id%3D16958960%26parameters%3Dsource%253Dembed%2526live_id%253D16966825%2526tvm_location%253Dtvm1_live%26_li%3D0%26_bot%3D0&livelist_1=%2Fapi%2Flive%2Flist%3Finclude_actions_p%3D1%26source%3Dembed%26live_id%3D16966825%26tvm_location%3Dtvm1_live%26upcoming_p%3D1%26ordering%3Dstreaming%26player_id%3D16958960&photolist_2=%2Fapi%2Fphoto%2Flist%3Fsize%3D10%26include_actions_p%3D1%26include_revision_p%3D1%26source%3Dembed%26live_id%3D16966825%26tvm_location%3Dtvm1_live%26player_id%3D16958960

I'm calling @Nintendocustom for this, since he holds the IPTV repl.

**Comment by Nintendocustom** [comment]
https://iptv--iptv.repl.co/Maltese/TVM/

**Comment by freearhey** [comment]
Closed in favor #2494
