### ISSUE TITLE
Fix: auto-update can eat your commit

### ISSUE THREAD

**Issue by Dum4G** [iptv-org/iptv#3503]
I've seen this before but thought it's just duplicate removing process. Can someone explain why this new channel has been removed?
https://github.com/iptv-org/iptv/commit/b69b6d60e4b5ca0da38b1c8554ab085e88f5688b#diff-d8c39b560d89eba29821a30c26b40ecb562f2bd2e12b24c40552dafccdd8c6ae

**Comment by LaneSh4d0w** [comment]
Then I wasn't dreaming when last time I've seen a few things disappear... I thought I had made a mistake.

**Comment by freearhey** [comment]
The channel was deleted because its name was the same as the blacklisted one from https://github.com/iptv-org/iptv/issues/1831

https://github.com/iptv-org/iptv/blob/6ba1c9b33fb129e2ff57f73cb3745345f44fcd0a/scripts/blacklist.json#L66



This is obviously a bug and as soon as I find a suitable solution I will update the script. In the meantime, we can return this link to the playlist simply by adding something to the channel name.

**Comment by LaneSh4d0w** [comment]
I think the most viable solution would be that we sort channels by Country
and then add their names.

It would limit the number of coincidential deletions.

**Comment by Dum4G** [comment]
I think suitable solution is to do a check for origin country as well

**Comment by LaneSh4d0w** [comment]
I think @Dum4G 's Lyngsat's listing could be useful in this situation.
