### ISSUE TITLE
German Channels missing!

### ISSUE THREAD

**Issue by darkspook1** [iptv-org/iptv#379]
ZDF
ZDF neo
ZDF info
das Erste
MDR
thanks in advance!

**Comment by darkspook1** [comment]
I've searched about them on google you can add them easily 
#EXTINF:-1,ZDF HD
https://zdf-hls-01.akamaized.net/hls/live/2002460/de/high/master.m3u8
#EXTINF:-1,ZDF info
https://zdfhls17-i.akamaihd.net/hls/live/744750/de/high/master.m3u8
#EXTINF:-1,ZDF neo
https://zdf-hls-02.akamaized.net/hls/live/2002461/de/high/master.m3u8
#EXTINF:-1,MDR Sachsen
https://mdrsnhls-lh.akamaihd.net/i/livetvmdrsachsen_de@513998/master.m3u8
#EXTINF:-1,MDR Sachsen-Anhalt
https://mdrsahls-lh.akamaihd.net/i/livetvmdrsachsenanhalt_de@513999/master.m3u8
#EXTINF:-1,MDR Thüringen
https://mdrthuhls-lh.akamaihd.net/i/livetvmdrthueringen_de@514027/master.m3u8

**Comment by lmazardo** [comment]
From my french ISP, I could not reach ZDF, I've the following errors.

```bash
vlc https://zdfhls17-i.akamaihd.net/hls/live/744750/de/high/master.m3u8                                                           
VLC media player 3.0.7 Vetinari (revision 3.0.7-0-g86cee31099)
[00005623089cb570] main libvlc: Running vlc with the default interface. Use 'cvlc' to use vlc without interface.                                    
[00007f68d0001690] access stream error: HTTP 403 error
[00007f68d031cd20] access stream error: HTTP 403 error
[00007f68d031cd20] access stream error: HTTP 403 error
[00007f68d0001520] access stream error: HTTP 403 error
[00007f68d0001520] access stream error: HTTP 403 error
[00007f68dc001810] access stream error: HTTP 403 error
[00007f68d0001520] access stream error: HTTP 403 error
[00007f68dc301b90] access stream error: HTTP 403 error


```

**Comment by darkspook1** [comment]
hmmm... from my German ISP, they work just fine! do I have to change something? I am relatively new in these things!

**Comment by darkspook1** [comment]
I've checked! they work only on German ISP! would add them or I doesn't make any sense adding them only for the people in Germany? :)

**Comment by freearhey** [comment]
We don’t add geo-blocked broadcasts, as they are too difficult to support.

**Comment by DocSniper** [comment]
A list of working German channels: 
[https://github.com/mediathekview/zapp/blob/master/app/src/main/res/raw/channels.json](https://github.com/mediathekview/zapp/blob/master/app/src/main/res/raw/channels.json)
However, I haven't tested if some of them are geo-blocked.

**Comment by freearhey** [comment]
@DocSniper Unfortunately, not all channels work (some are really geo-blocked), but I added the rest. 

Thanks for your help!

**Comment by DocSniper** [comment]
@freearhey  Glad, that i could help. :-)

But one more thing to the rejection of geo-blocking channels.

While I understand the problems of maintaining the geo-blocked channels, if you live in a country and are not blocked then you want to have all possible channels, otherwise the list is unfortunately almost worthless (in my opinion). For example, to build a full German TV on IP basis with Kodi, you also need ARD, ZDF and other channels.

Possible solutions:
- How about adding the geo-blocked channels to the lists and adding something like "(geo-blocked)" to the channel name, then people can guess that it's not playable abroad.
- Or alternatively, create a second list, e.g. as "[CountryCode]-geo-blocked.m3u". Then the standard m3u files would remain unchanged but as a resident you would have all the channels (when merging the lists).

Just a suggestion, I understand that this only complicates everything. ;-)

**Comment by freearhey** [comment]
@DocSniper We only recently discussed this with @boomski, so if you don’t mind, I just copy my point of view on this issue here:

To prevent playlists from becoming obsolete, the links in them must be constantly checked.

A couple of times a month I run a script on my computer that automatically goes through all 8000 links and checks if broadcasts are available. And for this script there is no difference the channel is geo-blocked or just does not work. The same thing with the VLC player, usually it does not even produce any errors.

At the same time, people from completely different places can use these playlists, and adding broadcasts limited to one/two countries to them seems a little unjustified to me.

That’s why I so much resist adding such links.

If someone is ready to write a script that can bypass geo-blocking, let me know. And then we can discuss how to store such links in the repository.

**Comment by darkspook1** [comment]
@DocSniper thanks for supporting. 
Actually I thank the most German speakers will be eventually in Germany. For checking purpose, man can apply tor or other VPN program and the people who suffer from the Geo-blocking can run a VPN program themselves on their computer or Android-Box.

**Comment by freearhey** [comment]
I created a new issue #480. Let's continue the discussion there so that the rest can also participate in it.
