### ISSUE TITLE
ORTM 1

### ISSUE THREAD

**Issue by alfus5** [iptv-org/iptv#3885]
Channel Name: ORTM1
Country: MALI (ML)
Language: FRENCH
External Link (optional): https://www.lyngsat.com/tvchannels/ml/ORTM-1.html
**Notes (optional):**General Channel

**Comment by MapGuy11** [comment]
Working On It

**Comment by MapGuy11** [comment]
http://79.137.86.98/satigui.m3u8

**Comment by MapGuy11** [comment]
ORTM 1: http://46.105.114.82/ortm.m3u8

**Comment by MapGuy11** [comment]
AFRICABLE: http://46.105.114.82/africable.m3u8

**Comment by MapGuy11** [comment]
ORTB: http://46.105.114.82/ortb.m3u8

**Comment by MapGuy11** [comment]
CRTV: http://46.105.114.82/crtv.m3u8

**Comment by MapGuy11** [comment]
These are all straight from their government's respected apps.

**Comment by MapGuy11** [comment]
NEED A WEB BROWSER USER AGENT IT SEEMS

**Comment by Dum4G** [comment]
![image](https://user-images.githubusercontent.com/5430116/128110514-d9dbf85e-fc7a-42df-ad0b-0dc11c675aa1.png)
Tried RTG, shows a single frame rn

**Comment by LaneSh4d0w** [comment]
> 
> 
> @alfu5 ORTM1: http://46.105.114.82/ortm.m3u8
> ORTM1: http://51.210.1.13:18000/ortm/hls/playlist.m3u8
> CHECK IF OK!

1st one is fine, the other has got a 2 minute difference and audio does not seem to be synchronized with the video.

**Comment by LaneSh4d0w** [comment]
West Africa TV : https://linkastream.co/headless?url=https://dai.ly/x6vbjdp

**Comment by LaneSh4d0w** [comment]
Espace TV : http://cdnamd-hls-globecast.akamaized.net/live/ramdisk/espace_tv/hls_video/index.m3u8

**Comment by LaneSh4d0w** [comment]
Right now accesses to those streams are forbidden, but those are official streams (might be because of copyrighted content not available on their streams.

RTI 1 Côte d'Ivoire : https://www.enovativecdn.com/rticdn/smil:rti1.smil/playlist.m3u8
RTI 2 Côte d'Ivoire : https://www.enovativecdn.com/rticdn/smil:rti2.smil/playlist.m3u8
RTI 3 Côte d'Ivoire : https://www.enovativecdn.com/rticdn/smil:rti3.smil/playlist.m3u8
RTI Bouaké Côte d'Ivoire : https://www.enovativecdn.com/rticdn/smil:rtibouake.smil/playlist.m3u8
Radio Côte d'Ivoire (Icecast stream it seems) : https://enovativecdn.com/radioci/icecast/playlist.m3u8

Only this one is working right now : 
Fréquence 2 Côte d'Ivoire : https://enovativecdn.com/frequence2/icecast/playlist.m3u8

**Comment by freearhey** [comment]
@MapGuy11 
> ORTM1: http://46.105.114.82/ortm.m3u8
ORTM1: http://51.210.1.13:18000/ortm/hls/playlist.m3u8

both links works great

![image](https://user-images.githubusercontent.com/7253922/128251912-67f4027a-c90e-4166-b385-ec88dccf5119.png)
