### ISSUE TITLE
CBS 2 Los Angeles KCBS

### ISSUE THREAD

**Issue by creeps125** [iptv-org/iptv#4338]
**Channel Name:** CBS 2
**Country:** USA (Los Angeles, CA)
**Language:** English
**Website:** losangeles.cbslocal.com

**Comment by jkemp814** [comment]
CBSN 2 Los Angeles, CA (KCBS-TV) is already in the playlist. 

CBS 9 Los Angeles, CA (KCAL-TV) it's sister station is also in the playlist.

**Comment by crackers8199** [comment]
CBSN is not KCBS

**Comment by jkemp814** [comment]
@crackers8199 We included both KCBS (CBSN) and KCAL because that's what's available from the network provider. KCBS-DT1 is not streaming live over the internet. It would have to be captured and re-streamed, and the link provided for it to be added to the list. Go to the website the OP posted and notice in the descriptions and content offered.
