### ISSUE TITLE
Cartoon Network Latin America (Brazilian feed)

### ISSUE THREAD

**Issue by cooldude2144** [iptv-org/iptv#4437]
**Channel Name:** Cartoon Network LA
**Channel ID:** CartoonNetworkBrazil.br
**Country:** Brazil
**Language:** Portugese, English
**Website:** spa.cartoonnetworkla.com
**Stream URL (optional):** xxx
**Notes (optional):*** xxx

**Comment by Dum4G** [comment]
Seems legit
https://www.youtube.com/channel/UCQySZQ6rrgJXRuonMwIIGMA/live

**Comment by LaneSh4d0w** [comment]
https://query-streamlink.herokuapp.com/iptv-query?streaming-ip=https://www.youtube.com/channel/UCQySZQ6rrgJXRuonMwIIGMA/live

**Comment by Dum4G** [comment]
According to weeky there're five feeds for LATAM region:
All five feeds are generated by central headquarters in Atlanta, Georgia and also broadcast both programming and continuity in English through SAP.

Mexico. Aimed at Mexico. It uses the Mexico City timezone as its main timezone. It is available to Central American countries on satellite TV provider Sky
South Atlantic feed: aimed at Argentina, Paraguay and Uruguay. It uses the Buenos Aires timezone as its main timezone.
North Atlantic Feed: aimed at Colombia, Venezuela, Central America and the Caribbean. It uses the Bogotá timezone as its main timezone.
Pacific feed: aimed at Chile, Ecuador, Peru and Bolivia. It uses the Santiago de Chile timezone as its main timezone.
Brazilian feed: independent feed for Brazil, with different programming and schedule. It uses the Brasília timezone as its main timezone
https://en.wikipedia.org/wiki/Cartoon_Network_(Latin_American_TV_channel)

Since we won't be capable to determine where the stream is intended to be broadcasted I can only suggest these two sources in Spanish

http://45.181.121.154:8000/play/a02k
http://38.131.11.9:1080/play/a012

**Comment by LaneSh4d0w** [comment]
> 
> 
> According to Wiki there're five feeds for LATAM region:
> All five feeds are generated by central headquarters in Atlanta, Georgia and also broadcast both programming and continuity in English through SAP.
> 
> Mexico. Aimed at Mexico. It uses the Mexico City timezone as its main timezone. It is available to Central American countries on satellite TV provider Sky
> South Atlantic feed: aimed at Argentina, Paraguay and Uruguay. It uses the Buenos Aires timezone as its main timezone.
> North Atlantic Feed: aimed at Colombia, Venezuela, Central America and the Caribbean. It uses the Bogotá timezone as its main timezone.
> Pacific feed: aimed at Chile, Ecuador, Peru and Bolivia. It uses the Santiago de Chile timezone as its main timezone.
> Brazilian feed: independent feed for Brazil, with different programming and schedule. It uses the Brasília timezone as its main timezone
> https://en.wikipedia.org/wiki/Cartoon_Network_(Latin_American_TV_channel)
> 
> Since we won't be capable to determine where the stream is intended to be broadcasted I can only suggest these two sources in Spanish
> 
> http://45.181.121.154:8000/play/a02k
> http://38.131.11.9:1080/play/a012

He said "Portuguese" on the language, so I'm assuming he's talking about the Brazilian feed.

**Comment by freearhey** [comment]
https://github.com/iptv-org/iptv/blob/13d2f470b7e5b647c0d24d4b6897c651d4b52971/streams/br.m3u#L258-L261
