### ISSUE TITLE
The CW East

### ISSUE THREAD

**Issue by Central302** [iptv-org/iptv#4612]
**Channel Name:** CW East
**Country:** USA
**Language:** English
**Website:** https://www.cwtv.com/
**Stream URL (optional):** xxx
**Notes (optional):** Need Eastern Feed of CW Affiliate Channel.

**Comment by MapGuy11** [comment]
I wish I had unlimited data to push the stream because this could be easily done.

**Comment by MapGuy11** [comment]
@Central302 I can offer 1080p HEVC 700kbps or 576p H264 streams because of my internet connect has a data cap on it. It will be through CW Flagship Station WPSG-DT1. Check out the video feed and see what you think. If I should drop the HEVC to 720p let me know. 
https://cdn007.the6tv.duckdns.org:2443/the6tv-hd/philadelphia/WPSG/playlist.m3u8

**Comment by Central302** [comment]
I'm Sorry, but I Can't Check the Stream.
But I'm ok that you can stream it in 576p.

**Comment by Central302** [comment]
Thank You! @MapGuy11 and I Close This Issuse

**Comment by spotanjo3** [comment]
It's dead link.
