### ISSUE TITLE
Fix: channels missing from a list they're supposed to be judging by their tvg-id

### ISSUE THREAD

**Issue by Owyn** [iptv-org/iptv#6705]
### Describe your issue

https://github.com/iptv-org/iptv/blob/master/streams/ru.m3u#L576
https://github.com/iptv-org/iptv/blob/master/streams/ru.m3u#L578
these two (`tvg-id="RBKTV.ru"` & `status="online"`) are missing from the output rus lang list: https://iptv-org.github.io/iptv/languages/rus.m3u
but 3rd one with the same tvg-id is present there as it should
https://github.com/iptv-org/iptv/blob/master/streams/ru.m3u#L580

even thought they all have the same tvt-id and should have same language set in their info by the bot

**Comment by freearhey** [comment]
This is due to the fact that only one link with the same id gets into the public playlists to avoid unnecessary repetitions.

However, links with "online" status should go into the playlists first. And that was indeed a bug.

Fixed in https://github.com/iptv-org/iptv/commit/a4aa6e7d1e0031f4e4163406d61d61e94436b3be
