### ISSUE TITLE
Replace: RUV

### ISSUE THREAD

**Issue by Albirew** [iptv-org/iptv#6932]
### Stream Title

RUV

### What happened to the stream?

Not loading

### Notes

Accessing RUV (iceland) on web browser shows "Run The Repl To see output." page. may be related.
feeds are still working on website https://www.ruv.is/sjonvarp/beint/ruv

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by Sphinxroot** [comment]
https://ruv-web-live.akamaized.net/streymi/ruverl/ruverl.m3u8

**Comment by Albirew** [comment]
is there an issue as for why this one and #6933 are still not integrated in master?

**Comment by Albirew** [comment]
closing here as feed has disappeared and a new issue to re-add it exists (#8166)

**Comment by freearhey** [comment]
> is there an issue as for why this one and https://github.com/iptv-org/iptv/issues/6933 are still not integrated in master?

It's just a matter of time. Since there are many requests, it is not always possible to process them all quickly.

If you want to speed up the process you can add a new link to the playlist yourself via [pull request](https://github.com/iptv-org/iptv/pulls), just read this [guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#add-or-replace-a-stream) before you do it.
