### ISSUE TITLE
Replace: Blue Ant Entertaintment [ID]

### ISSUE THREAD

**Issue by Rerererererere28** [iptv-org/iptv#7200]
### Stream Title

Blue ant entertainment

### What happened to the stream?

Not loading

### Possible Replacement

http://lb.fantom-tv.xyz:2095/live/3458/3458/21036.ts

### Notes

Broken

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by Rerererererere28** [comment]
Please ID subtitle link

**Comment by R4IN2007** [comment]
https://livecdn.fptplay.net/hda1/blueantent_hls.smil/chunklist_b2500000.m3u8
![20220429_180112](https://user-images.githubusercontent.com/83226646/166078773-9ad5e028-ff86-460c-95bd-35f776ef45ae.jpg)

**Comment by F640** [comment]
> https://vips-livecdn.fptplay.net/hda1/blueantent_hls.smil/chunklist_b2500000.m3u8

You mean this:
https://vips-livecdn.fptplay.net/hda1/blueantent_hls.smil/playlist.m3u8

**Comment by F640** [comment]
~Some random findings from this link:~
- ~Blue Ant Extreme (Rock Extreme): https://vips-livecdn.fptplay.net/hda1/blueantext_hls.smil/playlist.m3u8~
- ~HBO: https://vips-livecdn.fptplay.net/hda1/hbo_hls.smil/playlist.m3u8~
Off topic

**Comment by Rerererererere28** [comment]
> https://vips-livecdn.fptplay.net/hda1/blueantent_hls.smil/chunklist_b2500000.m3u8 ![20220429_180112](https://user-images.githubusercontent.com/83226646/166078773-9ad5e028-ff86-460c-95bd-35f776ef45ae.jpg)

Add thanks, but is not ID sub :(
#EXTINF:-1 group-title="[Live TV]-Entertainment" tvg-logo="https://i.ibb.co/Df5t6mP/blue-ant-enter-home-tv.png",[Indonesia] Blue ant entertainment
https://vips-livecdn.fptplay.net/hda1/blueantent_hls.smil/chunklist_b2500000.m3u8

**Comment by Rerererererere28** [comment]
> ~Some random findings from this link:~
> 
> * ~Blue Ant Extreme (Rock Extreme): https://vips-livecdn.fptplay.net/hda1/blueantext_hls.smil/playlist.m3u8~
> * ~HBO: https://vips-livecdn.fptplay.net/hda1/hbo_hls.smil/playlist.m3u8~
>   Off topic

Thanks Add for backup

**Comment by F640** [comment]
> Add thanks, but is not ID sub :(

Sadly, we have no control over that :/

**Comment by F640** [comment]
> > ~Some random findings from this link:~
> > 
> > * ~Blue Ant Extreme (Rock Extreme): https://vips-livecdn.fptplay.net/hda1/blueantext_hls.smil/playlist.m3u8~
> > * ~HBO: https://vips-livecdn.fptplay.net/hda1/hbo_hls.smil/playlist.m3u8~
> >   Off topic
> 
> Yeah There Some Other Channels With The Same Url (vips-livecdn.fptplay.net)
> 
> BBC EARTH https://vips-livecdn.fptplay.net/hda2/bbcearth_vhls.smil/chunklist_b2500000.m3u8
> 
> Cinemax https://vips-livecdn.fptplay.net/hda1/cinemax_hls.smil/chunklist.m3u8?NoxusPlus+.m3u8
> 
> Discovery Asia https://vips-livecdn.fptplay.net/hda2/discoveryasia_vhls.smil/chunklist_b5000000.m3u8
> 
> Discovery Channel https://vips-livecdn.fptplay.net/hda2/discovery_hls.smil/playlist.m3u8

Discovery Asia and Discovery Channel is banned in this repo (they got this [DMCA notice](https://github.com/iptv-org/iptv/issues/1831) because of these channels). What a dangerous finding! 😅

**Comment by F640** [comment]
Some more findings from this url:

BBC Lifestyle
https://vips-livecdn.fptplay.net/sdb/bbclifestyle_2000.stream/chunklist.m3u8

National Geographic
https://vips-livecdn.fptplay.net/hda2/natgeohd_vhls.smil/chunklist.m3u8

Outdoor channel (not sure what's the name)
https://vips-livecdn.fptplay.net/hda1/outdoorfhd_vhls.smil/chunklist.m3u8

Fashion TV (error 403)
http://vips-livecdn.fptplay.net/hda2/fashiontvhd_vhls.smil/chunklist.m3u8

Animax
https://vips-livecdn.fptplay.net/hda3/animaxport_vhls.smil/chunklist.m3u8

CBeebies
https://vips-livecdn.fptplay.net/hda3/cbeebies_vhls.smil/chunklist.m3u8

Baby First
https://vips-livecdn.fptplay.net/hda1/babyfirst_vhls.smil/chunklist.m3u8

Baby TV
https://vips-livecdn.fptplay.net/hda3/babytvhd_vhls.smil/chunklist.m3u8

Boomerang
https://vips-livecdn.fptplay.net/hda3/boomerang_vhls.smil/chunklist.m3u8

Cartoon Network (error 403)
https://vips-livecdn.fptplay.net/hda3/cartoonnetworkhd_vhls.smil/chunklist.m3u8

Da Vinci
https://vips-livecdn.fptplay.net/hda2/davincihd_vhls.smil/chunklist.m3u8

Dreamworks
https://vips-livecdn.fptplay.net/hda3/dreamworks_vhls.smil/chunklist.m3u8

Warner TV (error 403)
http://vips-livecdn.fptplay.net/hda3/warnertv_vhls.smil/chunklist.m3u8

Kix
https://vips-livecdn.fptplay.net/hda1/kixhd_vhls.smil/chunklist.m3u8

AXN (error 403)
http://vips-livecdn.fptplay.net/hda3/axnhd_vhls.smil/chunklist.m3u8

Cinema World (error 403)
https://vips-livecdn.fptplay.net/hda2/cinemawork_vhls.smil/chunklist.m3u8

Bloomberg (error 403)
https://vips-livecdn.fptplay.net/sdb/bloomberg_hls.smil/chunklist.m3u8

France 24
https://vips-livecdn.fptplay.net/sdb/france24_hls.smil/chunklist.m3u8

Arirang
https://vips-livecdn.fptplay.net/sdb/arirang_hls.smil/chunklist.m3u8

KBS World
https://vips-livecdn.fptplay.net/sdb/kbs_hls.smil/chunklist.m3u8

TV5 Monde Asie
https://vips-livecdn.fptplay.net/sdb/tv5_hls.smil/chunklist.m3u8

MTV
https://vips-livecdn.fptplay.net/sdb/mtv_hls.smil/chunklist.m3u8

National Geographic Wild
https://vips-livecdn.fptplay.net/hda3/natgeowild_vhls.smil/chunklist.m3u8

Some of these streams tokenized, But most of them still working. Probably their tokenization is broken (or not implemented correctly), luckily.
All these links must be opened without referrer or `https://fptplay.vn/`, otherwise error 403.
You can also replace `chunklist.m3u8` to `chunklist_b5000000.m3u8` to lock the video quality.
Video quality list:
- 1080p: `chunklist_b5000000.m3u8`
- 720p: `chunklist_b2500000.m3u8`
- 480p: `chunklist_b1800000.m3u8`
- 360p: `chunklist_b1200000.m3u8`

**Comment by LaneSh4d0w** [comment]
Is it this : http://210.210.155.35/dr9445/h/h16/index.m3u8 ?

**Comment by Rerererererere28** [comment]
> 

Thanks sir your the best
