### ISSUE TITLE
Add:  Noovo (French Canadian TV channel)

### ISSUE THREAD

**Issue by mikhoul** [iptv-org/iptv#7294]
### Channel Name

Noovo

### Channel ID

Noovo.ca

### Website

https://www.noovo.ca/

### Stream URL

https://pe-fa-lp03a.9c9media.com/live/NOOVO/p/hls/00000201/716cf4c845225692/manifest.m3u8

### Notes

Play fine in Tivimate + PerfectPlayer (both Audio **AND** video)

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment]
Not 24/7, per channel schedules.

**Comment by takethis2165** [comment]
no sound with vlc

**Comment by mikhoul** [comment]
VLC don't support the CODEC sadly.

**Comment by takethis2165** [comment]
ok thanks!

**Comment by mikhoul** [comment]
@LaneSh4d0w   Could you tell me when you expect Noovo will be added to the m3u ? 

I will remove it from my personal list.

Regards. :octocat:

**Comment by takethis2165** [comment]
It,s not working with vlc because of the codec!
________________________________
De : LaneSh4d0w ***@***.***>
Envoyé : 9 juin 2022 08:02
À : iptv-org/iptv ***@***.***>
Cc : takethis2165 ***@***.***>; Comment ***@***.***>
Objet : Re: [iptv-org/iptv] Add: Noovo (French Canadian TV channel) (Issue #7294)


Closed #7294<https://github.com/iptv-org/iptv/issues/7294> as completed via #7243<https://github.com/iptv-org/iptv/pull/7243>.

**Comment by mikhoul** [comment]
@djsly   I'm not the owner I just extracted the stream from Noovo website.
