### ISSUE TITLE
Add: Cuatro and Telecinco

### ISSUE THREAD

**Issue by trancer1994** [iptv-org/iptv#7984]
### Channel Name

Cuatro, Telecinco

### Website

https://www.cuatro.com/

### Stream URL

https://directos.cuatro.com/orilinear09/live/linear09/main/main.isml/web.m3u8?hdnts=st=1659976844~exp=1659977024~acl=/*~hmac=71139a690df9f963753a760817b1f5379b02da44a65ff29ff9924dcfea326928

### Notes

The URL I've given you doesn't actually work anymore (tokenised), but I hope it gives you an idea of what you are dealing with token-wise. The live page where you can find the channel and also see how they make the stream work is https://www.cuatro.com/en-directo/
Telecinco works much the same way. The streaming url for that channel is https://directos.telecinco.es/orilinear01/live/linear01/main/main.isml/web.m3u8?hdnts=st=1659978978~exp=1659979157~acl=/*~hmac=856d6681c51221c51f41f8c4baf3a0ddf15c7afa13cc7e33b26bd7ac85ea5dbc Its live page works the same as Cuatro. https://www.telecinco.es/endirecto/
These channels may already be in the playlists. If not, please add them. You will need to figure out how the security token is generated, or a way to bypass it, and may also need a Spanish VPN.

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by ztreamhd** [comment]
I have the JSON files needed to create those tokenized M3U8 streams, but there are two main problems regarding this:
1. You get every single piece of the token individually, which means you have to know how to decode and assemble it.
2. You need one specific IP address to work on, which means that, in case of creating a script to generate these links, you'll most likely have to add a ``X-Forwarded-For`` header in order to make them work, and I think that's not supported in most players (except for Kodi)

**Comment by freearhey** [comment]
> IMPORTANT: the issue should contain a request for only one channel, otherwise it will be closed immediately

https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel
