### ISSUE TITLE
Fix: Playlist EPGs in IPTV Merge

### ISSUE THREAD

**Issue by missjane63** [iptv-org/iptv#8301]
### Describe your issue

Checking to see if there is an issue with the EPGs when using the playlist with IPTV Merge.  Was working fine until yesterday, streams still work but no EPG

**Comment by LaneSh4d0w** [comment]
If your issue is concerning EPG, you are in the wrong repo. Please address it over https://github.com/iptv-org/epg.

**Comment by spotanjo3** [comment]
I don't know how to use EPG. Since I renamed some channels in notepad and save to m3u and m3u8 file and they works. Now, I want to use EPG. Its USA only. All I have to do is put url in television and it will read this file ? Or I do not supposed to rename some channels in notepad ? it would effected EPG ? Sorry about my English.
