### ISSUE TITLE
I have 500 sensitive live broadcast sources to crack the captured banana video. 

### ISSUE THREAD

**Issue by yuanxy** [iptv-org/iptv#834]
I have 500 sensitive live broadcast sources to crack the captured banana video.

**Comment by Jinkeezalhomse** [comment]
Bein Sport too??

**Comment by bermufine** [comment]
Bein Sport HD french or english ?

Congo channels also? (Mean Démocratic Républic of Congo)

Can you paste your source code Please

**Comment by bermufine** [comment]
Hello,
I am requesting an Congo channels, by the name of :
digital_congo
Heritage tv
Nyota tv
RTVS1
RTNC2
Antenne A
Rtg@.
Please Feel free To send me a working link in my gmail: Congomonpays243@gmail.com

Thank you, and have a wonderful day.

Good luck on future upgrades and keep up the work.

Also, if you can, please add HD streams of Tele50
B-ONE
RTNC
Mwangaza
Don't Forget SPORTS channels like Bein Sport HD from 1 To 12

Thank you once again.

**Comment by yuanxy** [comment]
Limited to the current laws of the mainland, I can't send them to you for the time being. These program sources and their overall clarity are OK, but they are all adult video.



 
From: bermufine
Date: 2019-12-23 12:35
To: iptv-org/iptv
CC: 舌尖上的胖胖; Author
Subject: Re: [iptv-org/iptv] I have 500 sensitive live broadcast sources to crack the captured banana video. (#834)
Hello,
I am requesting an Congo channels, by the name of :
digital_congo
Heritage tv
Nyota tv
RTVS1
RTNC2
Antenne A
Rtg@.
Please Feel free To send me a working link in my gmail: Congomonpays243@gmail.com
Thank you, and have a wonderful day.
Good luck on future upgrades and keep up the work.
Also, if you can, please add HD streams of Tele50
B-ONE
RTNC
Mwangaza
Don't Forget SPORTS channels like Bein Sport HD from 1 To 12
Thank you once again.

**Comment by bermufine** [comment]
Hi ALEKSANDR STATCIUK firstly I say thanks to replied my requests.But I my side is not working at all accepted TRACE KITOKO but tele50,RTNC, B-one and Digital Congo still not working I try with VLC and real player doesn't work , know that before was working every second weeks but looks like you updated then all was working only for 3 days then since last week till now doesn't work I send a piece joint of screenshots to show you how is writing.So I beg you to update again maybe will work permanently  then if there's away to add more Congo Democratic's Channels Have a nice day and hope yo resolve my queries Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Aleksandr Statciuk <notifications@github.com> Date: 23/12/2019  17:46  (GMT+00:00) To: iptv-org/iptv <iptv@noreply.github.com> Cc: bermufine <congomonpays243@gmail.com>, Manual <manual@noreply.github.com> Subject: Re: [iptv-org/iptv] I have 500 sensitive live broadcast sources to crack the captured banana video.  (#834) Closed #834.
