### ISSUE TITLE
Fix: Tele Liban shows as error

### ISSUE THREAD

**Issue by UltraHDR** [iptv-org/iptv#8676]
### Describe your issue

I think the link check doesn't use the referrer?

https://github.com/iptv-org/iptv/pull/8661/files#diff-54d5c420f584c12ed3e68ac63d0108d79fda66d3791b4ccc729c4a6171b519a0

**Comment by freearhey** [comment]
I just checked the link and it turns out that for some reason the server returns a "401 Unauthorized" error if the request comes from the American IP:

```sh
curl --referer https://www.teleliban.com.lb/live https://cdn.catiacast.video/abr/ed8f807e2548db4507d2a6f4ba0c4a06/playlist.m3u8
```

_Resonse w/o VPN:_

```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-STREAM-INF:BANDWIDTH=1438019,RESOLUTION=1280x720,CODECS="avc1.64001f,mp4a.40.2"
tl/mbs1/chunks.m3u8
```

_Resonse via US VPN:_

```
<html>
<head><title>401 Authorization Required</title></head>
<body>
<center><h1>401 Authorization Required</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

I have updated the script, and now such links will be marked with the status "blocked". This should fix this error.

**Comment by UltraHDR** [comment]
Thanks @freearhey
